
export const images = [
    "/images/grid/Candid.jpg",
    "/images/grid/CFG.jpg",
    "/images/grid/Cpt.jpg",
    "/images/grid/HH_Hall.jpg",
    "/images/grid/HH_Img.jpg",
    "/images/grid/HH_Logo.jpg",
    "/images/grid/HH_Poster.jpg",
    "/images/grid/Krangsuri.jpg",
    "/images/grid/KS_lake.jpg",
    "/images/grid/LLL.jpg",
    "/images/grid/SH_Camera.jpg",
    "/images/grid/SH_Cave.jpg",
    "/images/grid/WC_valley.jpg",
    "/images/grid/WC.jpg",
    "/images/grid/WF.jpg",
    "/images/grid/AP_Msk.jpg",
    "/images/grid/BP.png",
    "/images/grid/CFG_gp.jpg",
    "/images/grid/HH_Vr.jpg",
    "/images/grid/Hostel.jpg",
    "/images/grid/JPMC.jpg",
    "/images/grid/MT.jpg",
]

